### ISSUE TITLE
npm installation fails

### ISSUE THREAD

**Issue by giosifelis** [reepolee/svelte-vite-windi#1]
Hello,

I am getting this message:  

failed to load config from /Users/theBrain/node-projects/svelte/starting.templates/svelte-app/vite.config.js
error when starting dev server:
TypeError: (0 , import_vite_plugin_svelte.default) is not a function
    at /Users/theBrain/node-projects/svelte/starting.templates/svelte-app/vite.config.js:49:45
    at loadConfigFromFile (/Users/theBrain/node-projects/svelte/starting.templates/svelte-app/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:72015:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolveConfig (/Users/theBrain/node-projects/svelte/starting.templates/svelte-app/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:71600:28)
    at async createServer (/Users/theBrain/node-projects/svelte/starting.templates/svelte-app/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:70142:20)
    at async CAC.<anonymous> (/Users/theBrain/node-projects/svelte/starting.templates/svelte-app/node_modules/vite/dist/node/cli.js:13892:24)

I have the latest version of node.

do you have any idea why it fails?

**Comment by psucodervn** [comment]
In `vite.config.js`, just change from

```js
import svelte from "@sveltejs/vite-plugin-svelte";
```
to
```js
import { svelte } from "@sveltejs/vite-plugin-svelte";
```

**Comment by alesvaupotic** [comment]
So sorry I missed this one ... hopefully you fixed it. Closing for lack of activity.
